version: '3.1'

services:

  mysql:
    ports:
      - 3306:3306
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senha123
      MYSQL_DATABASE: rasplus
      MYSQL_USER: rasmoo
      MYSQL_PASSWORD: senha123

