version: '3.8'

services:

  mysql:
    image: mysql
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senha123
      MYSQL_DATABASE: rasplus
      MYSQL_USER: rasmoo
      MYSQL_PASSWORD: senha123
#    volumes:
#      - mysql_data_container:/data/db

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: rasmoo
      MONGO_INITDB_ROOT_PASSWORD: senha123
    ports:
      - 27017:27017
#    volumes:
#      - mongo_data_container:/data/db
#
#volumes:
#  mysql_data_container:
#  mongo_data_container:

